### ISSUE TITLE
TODO for the official announcement

### ISSUE THREAD

**Issue by sw005320** [isca-sig-rosp/ISCA-SIG-RoSP#1]
- [ ] add recent robust speech processing database ([CHiME-5](http://spandh.dcs.shef.ac.uk/chime_challenge/), [VOiCES](https://www.sri.com/work/publications/voices-obscured-complex-environmental-settings-voices-corpus), [Fearless Steps Challenge](http://fearlesssteps.exploreapollo.org/), [DIHARD](https://coml.lscp.ens.fr/dihard/index.html) etc.)
- [ ] make the dataset table sortable
- [x] move the datasets page from wiki to the main markdown document.
- [ ] move RIRs etc. and software pages here
- [x] create a noise database #2 
- [ ] add more (SIG) events
- [ ] add a page of how to contribute
- [x] add a logo 
- [ ] install a leaderboard function

**Comment by sw005320** [comment]
@ramon-astudillo, please suggest any comments about the page. We want to release it.

**Comment by ramon-astudillo** [comment]
sent an email :)

**Comment by sw005320** [comment]
I think the most items are done.
So, we can close this issue.
